### PR TITLE
Add run tasks once for multiple hosts

### PR DESCRIPTION
**Pull request by kea**

### CODE REVIEW

**Comment by micheleorselli** [comment]
Makes sense to me, I'm not convinced on continuing adding stuff to the Idephix class :-)

**Comment by ftassi** [comment]
@kea can you describe the use case for this?

**Comment by kea** [comment]
`idxfile.php`
```php
<?php

function deploy(Context $c) {
    $newVersionNumber = $c->executeOnce('prepareArtifact');
    $c->pleasePutMyFileOnServer($c, $newVersionNumber);
}

function prepareArtifact() {
    // git pull, build fe, pack, ...
    return date('YmdHis');
}

function pleasePutMyFileOnServer(Context $c, $newVersionNumber) {
    // ...
    $nextRelease = "/var/www/releases/".$newVersionNumber;
    $c->rsyncProject($nextRelease, $localArtifact . '/', $rsyncExclude);
}
```

`idxrc.php`
```php
<?php

$environments = ['prod' => [
    'hosts' => function () {
        $ec2client = new \Aws\Ec2\Ec2Client([
            'region' => 'eu-west-1',
            'version' => '2015-10-01'
        ]);
        ...
        return $ips;
]];
```

When I deploy on multiple hosts I want to prapare the artifact only once.

**Comment by ftassi** [comment]
I would prefer to leave such behaviours to the developer rather then exposing a specific method. We should allow the user to use the `Context` object to store persistent information across the tasks. Such information could be easily used directly from the idxfile and satisfy your use case.

Something like 
```
function prepareArtifact(Context $context) {
    // git pull, build fe, pack, ...
    if($context['artifactPrepared']) {
        return
    }

    $context['artifactPrepared'] = true
    return date('YmdHis');
}
```

**Pull request merged**
