### PR TITLE
Enable new idxfile format

### PR DESCRIPTION
**Pull request by ftassi**
after #50  I'm working on an implementation that will let idx to parse an idxfile like:

```
//When a function name will conflict with a php reserved key 
//and _ could be added. Idx should remove it and use "echo" 
//as task name
function echo_($value)
        echo $value;
}

// This would add a "greet" command
function greet($idx, $name) {
        $idx->runTask('echo', 'Ciao ' . $name);
    }

// This will add a 'deploy' and 'phpunit' library 
$deploy = new Deploy();
$phpunit = new PHPUnit();
```

and a separated `idxrc.php` with all the configurations defined as `$targets` variable:
```
$targets = array(
// bla bla bla
);
```

* [ ] ~~Doc block parsing for tasks descriptions~~
* [x] ~~Port legacy deploy extension~~ Write how to use legacy extensions
* [x] Update init task to create a  `idxrc.php` and `idxfile.php`
* [ ] ~~Update doc~`
* [X] _Maybe if not to costly_ Improve some kind of idxfile format recognizer so we can, at least, notify the user the he needs to update his idxfile format (if not convert it for him).

### CODE REVIEW

**Comment by ftassi** [comment]
I've implemented a couple of incomplete tests that will be tricky to mark as done. As I'm just parsing the code I don't have informations about the "scope" of the variables, I'm just seeing them as 'token', or 'node' of a script. Given that it's not that easy to distinguish a `$targets` variable defined in the root scope, from a `$targets` variable defined within a task (and I don't want to use the latter for configurations)

We could implement a custom NodeVisitor that add information about the scope in every node, but I'm not sure it will be worth it.

We could avoid variables and prefer functions instead, like this:
```
function idx_targets(){
    return ['foo' => 'bar'];
}
```

we could define some reserved functions such as `idx_targets()` `idx_ssh_client` `idx_libraries`. This should work and should be easy to implement, but *the user will have to know these reserved functions* (even right now he has to know the name of the special variables).

I don't know if using more reflection over parsing can help us here.

**Comment by micheleorselli** [comment]
The part regarding function parsing is ok. I'm not sure about the approach of having some variables defined by convention (```$target, $libraries``` and so on). I think we should find a way to make this part a bit more intuitive, for instance: 
- splitting task definition and configuration in separate files: it's something done by a lot of build tools (ant, phing, pake)
- find a way to create reusable functions: do we need libraries at all? What if we just rely on what php offers (like include)?

Using predefined function like ```idx_targets()``` is the approach choosen by pake (https://github.com/indeyets/pake). It could be a way but as you said it's something the users must know
 
Maybe we should try to define some use cases, like:
- simple task automation
- continuous integration
- continuous delivery
- reusing tasks
and so on, and see the best fitting format. What do you think?

**Comment by ftassi** [comment]
I'll definitely :+1:  for removing libraries for includes. If we can have an idxfile that contains only task definitions we can avoid libraries and the the user compose his idxfile including as many as he wants. Idephix should only take care of naming overlapping (just alerting the user or, event better, allowing some namespacing).

**Comment by ftassi** [comment]
A dedicated configuration file could be a nice solution, I'd prefer this instead of reserved functions. Even this introduce some complexity for the user though: he will have to deal with two different files.

**Comment by ftassi** [comment]
I guess this is it. 
I want to do some extra tweaking at the code, but the idxfile format should be it. After this the user would have:
- an idxfile.php containing only task defined as simple plain PHP functions. 
- an idxrc.php file containing a definition of targets. 

This should allow us to compose tasks from many idxfiles (as they were recipes in cookbook for the project). Also we don't need the libraries anymore.

I'll update the description of the PR according to the news decisions discussed with @kea

**Comment by fain182** [comment]
What about making the name a little bit more explicit, something like `idx_task.php` and `idx_target.php`?

**Comment by micheleorselli** [comment]
`idxfile.php` is consistent with the convention adopted by other tools:
- capistrano has `Capfile`
- fabric has `fabfile`
- rake has `rakefile`
and so on. What I find less explicit is the name `idxrc.php`. What is supposed to contain? Configuration?

**Comment by ftassi** [comment]
I can't remember were I saw a xxrc file for configurations, but I liked it. That file should support the definition of targets and other stuff (eg the chosen SSH client if any, and maybe custom input and output implementations). I guess we can say that it will contains generically `configurations`. 

I rather prefer not to bind the name of that file to the concept of `targets`, we may want to loose it or change it in the future, I'd prefer to keep it more generic (maybe idxrc.php is not that intuitive though). 

Also, as discussed in #40 we should decide if we want to keep 2 files in the root project, and have to separate options, ore maybe go for a `idx` directory which will contains both of them and have a single option to configure the configuration dir.

**Comment by dymissy** [comment]
`xxrc` files are used for example from bower (`.bowerrc`) of jshint (`.jshintrc`) in order to include configurations. E.g. in Bower you can define a custom directory for bower components through this file.

**Comment by ftassi** [comment]
ok, it's about time to pick some names :D 
I guess we all agree on `idxfile` for the tasks file. 

What about the configurations? Here are some suggestions:

- idxconfig
- idxenv
- idxrc

- feel free to add your suggestion here

**Comment by dymissy** [comment]
:+1: idxrc


Il sabato 19 settembre 2015, Francesco Tassi <notifications@github.com> ha
scritto:

> ok, it's about time to pick some names :D
> I guess we all agree on idxfile for the tasks file.
>
> What about the configurations? Here are some suggestions:
>
>    - idxconfig
>    - idxenv
>    -
>
>    idxrc
>    -
>
>    feel free to add your suggestion here
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ideatosrl/Idephix/pull/51#issuecomment-141585797>.
>


-- 
Simone D'Amico
Web Developer
Mobile:  +39 340.8652066
Skype: dymissy

Web:   http://simonedamico.com
Mail:  info@simonedamico.com
AboutMe: http://about.me/damicosimone

**Comment by fain182** [comment]
If you want keep it generic, following the unix tradition `idxrc` seems good to me.

**Comment by ftassi** [comment]
Merged into master

**Comment by drAlberT** [comment]
@dymissy  http://www.catb.org/jargon/html/R/rc-file.html ;)

**Pull request closed without merging**
