### PR TITLE
Print output of remote commands

### PR DESCRIPTION
**Pull request by danielsan80**
The remote has the same rights of the local. I like to know what he has to say.

### CODE REVIEW

**Comment by fain182** [comment]
I think we should show output of the remote commands, maybe we can merge this?

**Comment by ftassi** [comment]
👎  for fa7e62e
👍 for 0cfce7b

**Comment by ricfrank** [comment]
👍

**Comment by micheleorselli** [comment]
no test no party :-D

**Comment by ftassi** [comment]
Added some tests and merged. Thanks @danielsan80

**Pull request closed without merging**
