### PR TITLE
exit with status code 1 when there are errors

### PR DESCRIPTION
**Pull request by fain182**
This should fix the #58

### CODE REVIEW

**Comment by ricfrank** [comment]
+1

**Comment by fain182** [comment]
Adding a test I found that there are bigger problems, actually the example idx file doesn't work, because:

**`./bin/idx -c tests/idxfile.php echo 'pippo'`**
```
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Too many arguments.' in /Users/fain182/Documents/Lavori/Ideato/Idephix/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php:181
Stack trace:
#0 /Users/fain182/Documents/Lavori/Ideato/Idephix/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php(90): Symfony\Component\Console\Input\ArgvInput->parseArgument('pippo')
#1 /Users/fain182/Documents/Lavori/Ideato/Idephix/vendor/symfony/console/Symfony/Component/Console/Input/Input.php(61): Symfony\Component\Console\Input\ArgvInput->parse()
#2 /Users/fain182/Documents/Lavori/Ideato/Idephix/src/Idephix/bootstrap.php(14): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#3 /Users/fain182/Documents/Lavori/Ideato/Idephix/bin/idx(21): Idephix\run()
#4 {main}
  thrown in /Users/fain182/Documents/Lavori/Ideato/Idephix/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php on line 181
```

The problem is even in the branch master and the reason is that the command is parsed before reading the idxfile in https://github.com/ideatosrl/Idephix/blob/master/src/Idephix/bootstrap.php#L14 .

@ftassi any ideas to fix it? Maybe in bootstrap.php we should parse the command without the symfony console component?

**Comment by ftassi** [comment]
mmm I'm not able to replicate the issue on php 5.6

**Comment by fain182** [comment]
now that the problem with tests are solved you should see the error even on PHP 5.6: https://travis-ci.org/ideatosrl/Idephix/jobs/131344647

I will try to remove the console component from this file, if there aren't better solutions...

**Comment by fain182** [comment]
The status code problem has been solved.
I needed to change the run() to use exception instead of return to show errors, because old style idx file are included and is not possible to recover the return of the last line of an included file.

The build is still failing because of the bug https://github.com/ideatosrl/Idephix/issues/65 but the test https://github.com/ideatosrl/Idephix/blob/exit-status-code/tests/functional/ExitStatusCodeTest.php confirm that status code are working now.

**Pull request merged**
